spring:
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
            # - FilterToSetResponseCookie=Hello from Example Gateway Filter, CookieFilter, CookieValue
            - name: FilterToSetResponseCookie
              args:
                message: Hello from Example Gateway Filter
                cookieName: CookieFilter2
                cookieValue: CookieValue2

        - id: items-service
          uri: lb://items-service
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request-header, TestRequest123
            - AddResponseHeader=token-response-header, Test123
            - AddRequestParameter=token-request-parameter, TestParameter123
